apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: trakiya3939/docker-fastapi:11635647b470b30e5790b72b3c2ba8fc1df10da4
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
